#!/usr/bin/env python3
import sys
import os

if len(sys.argv) < 3 or len(sys.argv) == 4:
  print("Malformatted parameters. Module parameters: <name> [xresolution] [yresolution]")
  exit()

name = sys.argv[2]
target_dir = sys.argv[1]
new_module_dir = os.path.join(target_dir, "__BERYL__")
x_resolution = "1024"
y_resolution = "768"

if len(sys.argv) == 5:
  x_resolution = sys.argv[3]
  y_resolution = sys.argv[4]

print("creating featherkit project " + name)

for root, subFolders, files in os.walk(new_module_dir,topdown=False):
  this_folder = os.path.join(target_dir, root)
  for single_file in files:
    this_file = os.path.join(this_folder, single_file)
    this_file_tmp = this_file + ".tmp"
    file_read = open(this_file, 'r')
    file_write = open(this_file_tmp, 'w')
    for line in file_read:
      file_write.write(line.replace(
        '__BERYL_NAME__', name).replace(
        '__BERYL_CNAME__', name.capitalize()).replace(
        '__BERYL_XRES__', x_resolution).replace(
        '__BERYL_YRES__', y_resolution))
    file_read.close()
    file_write.close()
    os.rename(this_file_tmp, this_file)

    single_file_renamed = single_file.replace("__BERYL__", name);

    if(single_file != single_file_renamed):
      this_file_renamed = os.path.join(this_folder, single_file_renamed)
      os.rename(this_file, this_file_renamed)

os.rename(new_module_dir, name)
